from Programa import Programa

#Script Criado para testar os principais métodos e classes do programa


titulos = ['Vida e vida','Terra plana','Felicidade','Coerencia e explanada','Robos minimos','Dia escuro']
categorias = ['Esporte','Politica','Tecnologia','Politica','Tecnologia','Esporte']
datas = ['2021/10/10','2010/10/20','2020/05/03','2020/10/20','2021/01/05','2001/04/01']
textos = ['O empenho em analisar o aumento do diálogo entre os diferentes setores produtivos auxilia a preparação e a composição das condições inegavelmente apropriadas. No entanto, não podemos esquecer que a consulta aos diversos militantes assume importantes posições no estabelecimento das direções preferenciais no sentido do progresso. É importante questionar o quanto a crescente influência da mídia facilita a criação do sistema de formação de quadros que corresponde às necessidades.',
'  Todavia, o acompanhamento das preferências de consumo estimula a padronização das diretrizes de desenvolvimento para o futuro. Percebemos, cada vez mais, que a expansão dos mercados mundiais agrega valor ao estabelecimento dos índices pretendidos. Pensando mais a longo prazo, o julgamento imparcial das eventualidades obstaculiza a apreciação da importância do processo de comunicação como um todo. O que temos que ter sempre em mente é que a hegemonia do ambiente político garante a contribuição de um grupo importante na determinação dos métodos utilizados na avaliação de resultados. Gostaria de enfatizar que o comprometimento entre as equipes exige a precisão e a definição de todos os recursos funcionais envolvidos.',
'A nível organizacional, a necessidade de renovação processual possibilita uma melhor visão global das posturas dos órgãos dirigentes com relação às suas atribuições. Não obstante, a revolução dos costumes desafia a capacidade de equalização dos modos de operação convencionais. Ainda assim, existem dúvidas a respeito de como a estrutura atual da organização deve passar por modificações independentemente das diversas correntes de pensamento. Neste sentido, a competitividade nas transações comerciais pode nos levar a considerar a reestruturação das regras de conduta normativas. O incentivo ao avanço tecnológico, assim como o surgimento do comércio virtual oferece uma interessante oportunidade para verificação do orçamento setorial. A certificação de metodologias que nos auxiliam a lidar com a contínua expansão de nossa atividade não pode mais se dissociar da gestão inovadora da qual fazemos parte. Todas estas questões, devidamente ponderadas, levantam dúvidas sobre se a constante divulgação das informações nos obriga à análise do fluxo de informações. No mundo atual, o início da atividade geral de formação de atitudes ainda não demonstrou convincentemente que vai participar na mudança das formas de ação.',
'O cuidado em identificar pontos críticos no fenômeno da Internet aponta para a melhoria de alternativas às soluções ortodoxas. Do mesmo modo, a adoção de políticas descentralizadoras talvez venha a ressaltar a relatividade do retorno esperado a longo prazo. Por conseguinte, a valorização de fatores subjetivos causa impacto indireto na reavaliação das condições financeiras e administrativas exigidas. Podemos já vislumbrar o modo pelo qual a percepção das dificuldades apresenta tendências no sentido de aprovar a manutenção dos paradigmas corporativos. Evidentemente, o entendimento das metas propostas é uma das consequências do investimento em reciclagem técnica.',
' No entanto, não podemos esquecer que a estrutura atual da organização deve passar por modificações independentemente das diversas correntes de pensamento. Neste sentido, a mobilidade dos capitais internacionais pode nos levar a considerar a reestruturação do sistema de participação geral. Todas estas questões, devidamente ponderadas, levantam dúvidas sobre se o julgamento imparcial das eventualidades causa impacto indireto na reavaliação do processo de comunicação como um todo. A certificação de metodologias que nos auxiliam a lidar com a contínua expansão de nossa atividade talvez venha a ressaltar a relatividade dos procedimentos normalmente adotados. Por conseguinte, a constante divulgação das informações prepara-nos para enfrentar situações atípicas decorrentes dos modos de operação convencionais.',
 'Percebemos, cada vez mais, que a adoção de políticas descentralizadoras maximiza as possibilidades por conta dos relacionamentos verticais entre as hierarquias. O que temos que ter sempre em mente é que a necessidade de renovação processual assume importantes posições no estabelecimento dos conhecimentos estratégicos para atingir a excelência. Assim mesmo, a complexidade dos estudos efetuados ainda não demonstrou convincentemente que vai participar na mudança das direções preferenciais no sentido do progresso.']

run = Programa()
for i in range(len(titulos)):
  run.cadastrar_artigo(titulos[i],categorias[i],datas[i],textos[i])


run.gerar_relatorio_similaridade()
